# Alertmanager URL
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/web?/external_url
  value: https://alertmanager.((/bosh-director-test/shared/system_domain))

# Prometheus URL
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/web?/external_url
  value: https://prometheus.((/bosh-director-test/shared/system_domain))

# Grafana URL
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/server?/root_url
  value: https://grafana.((/bosh-director-test/shared/system_domain))

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus?/tls_skip_verify
  value: ((skip_ssl_verify))

# Route Registrar
- type: replace
  path: /instance_groups/name=nginx/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=nginx/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment_name))
    properties:
      route_registrar:
        routing_api:
          skip_ssl_validation: ((skip_ssl_verify))
        routes:
          - name: alertmanager
            registration_interval: 20s
            port: 9093
            uris:
              - alertmanager.((/bosh-director-test/shared/system_domain))
          - name: prometheus
            registration_interval: 20s
            port: 9090
            uris:
              - prometheus.((/bosh-director-test/shared/system_domain))
          - name: grafana
            port: 3000
            registration_interval: 60s
            uris:
              - grafana.((/bosh-director-test/shared/system_domain))

# Releases
- type: replace
  path: /releases/-
  value:
    name: bpm
    version: 1.1.3
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.3
    sha1: b41556af773ea9aec93dd21a9bbf129200849eed

- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.191.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.191.0
    sha1: 8d6e700e43c0312614364cf4e84f0ac63b931a9e

